/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp6lab1.ventanas;

import tp6lab1.entidades.Directorio;

/**
 *
 * @author thefl
 */
public class Menu extends javax.swing.JFrame {
public static Directorio miDirectorio = new Directorio();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mbAdministracion = new javax.swing.JMenu();
        miAgregarClientes = new javax.swing.JMenuItem();
        miBuscarCliente = new javax.swing.JMenuItem();
        miBorrarCliente = new javax.swing.JMenuItem();
        mbSalir = new javax.swing.JMenu();
        miSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 356, Short.MAX_VALUE)
        );

        mbAdministracion.setText("Administracion");

        miAgregarClientes.setText("Agregar clientes");
        miAgregarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarClientesActionPerformed(evt);
            }
        });
        mbAdministracion.add(miAgregarClientes);

        miBuscarCliente.setText("Buscar cliente");
        miBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscarClienteActionPerformed(evt);
            }
        });
        mbAdministracion.add(miBuscarCliente);

        miBorrarCliente.setText("Borrar cliente");
        miBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBorrarClienteActionPerformed(evt);
            }
        });
        mbAdministracion.add(miBorrarCliente);

        jMenuBar1.add(mbAdministracion);

        mbSalir.setText("Salir");

        miSalir.setText("Salir del sistema");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        mbSalir.add(miSalir);

        jMenuBar1.add(mbSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miAgregarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarClientesActionPerformed
        // TODO add your handling code here:
        ViewAgregarClientes ac = new ViewAgregarClientes();
        escritorio.removeAll();
        escritorio.repaint();
        ac.setVisible(true);
        escritorio.add(ac);
        escritorio.moveToFront(ac);
    }//GEN-LAST:event_miAgregarClientesActionPerformed

    private void miBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscarClienteActionPerformed
        // TODO add your handling code here:
        ViewBuscarCliente buc = new ViewBuscarCliente();
        escritorio.removeAll();
        escritorio.repaint();
        buc.setVisible(true);
        escritorio.add(buc);
        escritorio.moveToFront(buc);
    }//GEN-LAST:event_miBuscarClienteActionPerformed

    private void miBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBorrarClienteActionPerformed
        // TODO add your handling code here:
        ViewBorrarClientes boc = new ViewBorrarClientes();
        escritorio.removeAll();
        escritorio.repaint();
        boc.setVisible(true);
        escritorio.add(boc);
        escritorio.moveToFront(boc);
    }//GEN-LAST:event_miBorrarClienteActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mbAdministracion;
    private javax.swing.JMenu mbSalir;
    private javax.swing.JMenuItem miAgregarClientes;
    private javax.swing.JMenuItem miBorrarCliente;
    private javax.swing.JMenuItem miBuscarCliente;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
